"""Download the chosen notebooks and turn them into playable opponents.

THE SOURCE IS THE NOTEBOOK'S OUTPUT, not its code. Simulation competitions are
submitted as a `submission.tar.gz` with a `main.py` inside, and the notebook
GENERATES it: its source is usually a base64 blob that writes the file, so
extracting the cells gave a module with no `agent` -7 of 15 failures- or a
`SyntaxError`. `kernels_output` hands it over already built, and it also avoids
executing downloaded code just to extract it.

The tar also carries data (`model.json`, `actions.json`) that `main.py` opens by
RELATIVE path: hence the `FileNotFoundError`s. That is why the module written
into `agents_pub/` is a hook that imports `main.py` from ITS directory.

MANDATORY VALIDATION: every opponent plays a full 24h x 30d game against the
do-nothing agent. An opponent that crashes or hangs halfway contaminates the
whole rung without warning. For reference, v48 plays 720 turns in 0.1 s, so the
300 s limit is 3,000 times normal.

Usage:  python tools/download_ladder.py            # data/chosen_ladder.json
        python tools/download_ladder.py <ref> ...  # specific notebooks
"""
import json, os, re, subprocess, sys, tarfile, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

DEST = os.path.join(ROOT, "agents_pub")
RAW = os.path.join(ROOT, "data", "public_agents")
HOOK = '''"""Generated by tools/download_ladder.py - do not edit by hand.

Loads the `main.py` from the submission.tar.gz of notebook {ref!r}.
The `chdir` is so its relative file reads (model.json, actions.json) find their
data; it only lasts for the import.
"""
import importlib.util, os

_DIR = {dir_!r}
_spec = importlib.util.spec_from_file_location({mod!r}, os.path.join(_DIR, "main.py"))
_mod = importlib.util.module_from_spec(_spec)
_prev = os.getcwd()
os.chdir(_DIR)
try:
    _spec.loader.exec_module(_mod)
finally:
    os.chdir(_prev)
agent = _mod.agent
'''


def body(ipynb_path):
    """Fallback: the notebook's code, when there was no usable output."""
    nb = json.load(open(ipynb_path, encoding="utf-8"))
    cells = [c for c in nb.get("cells", []) if c.get("cell_type") == "code"]
    written, rest = [], []
    for c in cells:
        src = "".join(c.get("source", []))
        m = re.match(r"\s*%%writefile\s+(\S+\.py)\s*\n", src)
        if m:
            written.append(src[m.end():])
        elif not re.match(r"\s*%%", src):
            rest.append("\n".join(l for l in src.splitlines()
                                  if not re.match(r"\s*[%!]", l)))
    return "\n\n".join(written or rest)


def from_output(api, ref, dst):
    """Download the notebook output and leave `main.py` ready. Dir or None."""
    out_dir = os.path.join(dst, "output")
    sub = os.path.join(dst, "sub")
    if os.path.isfile(os.path.join(sub, "main.py")):
        return sub
    os.makedirs(out_dir, exist_ok=True)
    api.kernels_output(ref, path=out_dir)
    tgz = [os.path.join(r, f) for r, _, fs in os.walk(out_dir)
           for f in fs if f.endswith((".tar.gz", ".tgz"))]
    for t in tgz:
        try:
            os.makedirs(sub, exist_ok=True)
            with tarfile.open(t) as tf:
                tf.extractall(sub, filter="data")
        except Exception:
            continue
        if os.path.isfile(os.path.join(sub, "main.py")):
            return sub
    # no tar: sometimes the output carries the .py on its own
    for r, _, fs in os.walk(out_dir):
        for f in fs:
            if f == "main.py" or (f.endswith(".py") and re.search(
                    r"^\s*def agent\s*\(",
                    open(os.path.join(r, f), encoding="utf-8",
                         errors="replace").read(), re.M)):
                os.makedirs(sub, exist_ok=True)
                import shutil
                for g in os.listdir(r):
                    shutil.copy(os.path.join(r, g), sub)
                os.rename(os.path.join(sub, f), os.path.join(sub, "main.py"))
                return sub
    return None


def validate(name_, seconds=300):
    """Import the module and play a whole game. Returns (ok, money, note).

    In a SUBPROCESS on purpose: downloaded code that hangs or aborts the
    interpreter must not take this process with it.
    """
    probe = f'''
import sys
sys.path.insert(0, {ROOT!r})
from kagsym import spec
from kagsym.environment import load_public
from kagsym.fastenv import FastEnv
spec.set_turns_per_day(24); spec.set_episode_steps(24*30)
ag = load_public({name_!r})
env = FastEnv(configuration={{"episodeSteps":24*30,"turnsPerDay":24,
                             "startingMoney":3000}}, seed=4242)
o = env.reset()
while not env.done:
    try:
        a = ag(o[0])
    except Exception as e:
        print("CRASHES", type(e).__name__, str(e)[:60]); raise SystemExit(2)
    o, _ = env.step([a, {{"farmer":["PASS"],"hands":[],"market":[]}}])
print("OK", int(env.rewards()[0]))
'''
    try:
        p = subprocess.run([sys.executable, "-c", probe], cwd=ROOT,
                           capture_output=True, text=True, timeout=seconds)
    except subprocess.TimeoutExpired:
        return False, 0, f"hangs (>{seconds}s; v48 takes 0.1 s)"
    out = (p.stdout or "").strip().splitlines()
    if out and out[-1].startswith("OK"):
        return True, int(out[-1].split()[1]), "ok"
    err = (p.stderr or p.stdout or "").strip().splitlines()
    return False, 0, (err[-1][:60] if err else "no output")


def install(api, entry):
    """Download one notebook and write its hook into `agents_pub/`."""
    ref = entry["ref"]
    name_ = entry.get("name") or ref.split("/")[-1]
    dst = os.path.join(RAW, name_)
    os.makedirs(dst, exist_ok=True)
    sub = from_output(api, ref, dst)
    if sub is None:
        return name_, False, "no main.py in the output"
    os.makedirs(DEST, exist_ok=True)
    mod = "pub_" + re.sub(r"[^A-Za-z0-9_]", "_", name_)
    with open(os.path.join(DEST, name_ + ".py"), "w", encoding="utf-8") as f:
        f.write(HOOK.format(ref=ref, dir_=sub, mod=mod))
    ok, money, note = validate(name_)
    return name_, ok, (f"${money}" if ok else note)


if __name__ == "__main__":
    import kaggle
    api = kaggle.KaggleApi(); api.authenticate()
    t0 = time.time()
    refs = [a for a in sys.argv[1:] if not a.startswith("-")]
    if refs:
        entries = [{"ref": r, "name": r.split("/")[-1]} for r in refs]
    else:
        entries = json.load(open(os.path.join(ROOT, "data", "chosen_ladder.json")))
    print(f"{len(entries)} notebooks -> agents_pub/, each validated with a "
          f"full 24h x 30d game\n")
    valid = []
    for i, e in enumerate(entries, 1):
        try:
            name_, ok, note = install(api, e)
        except Exception as ex:
            name_, ok, note = e["ref"], False, f"{type(ex).__name__}: {str(ex)[:50]}"
        print(f"  {i:>3}/{len(entries)}  {'ok ' if ok else 'BAD'}  "
              f"{name_[:52]:<54}{note}", flush=True)
        if ok:
            valid.append({**e, "name": name_,
                          "strength": int(note.lstrip('$') or 0)})
    out = os.path.join(ROOT, "data", "valid_ladder.json")
    json.dump(valid, open(out, "w"), indent=1)
    print(f"\n  {len(valid)}/{len(entries)} play. -> {out}  "
          f"({time.time()-t0:.0f}s)")
